// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqLL8GSUk8nxC0phtiEnkHLLz88XgStyo',
    appId: '1:303720759928:android:2914374d193bc1abe8e38d',
    messagingSenderId: '303720759928',
    projectId: 'diabetes-health-check',
    storageBucket: 'diabetes-health-check.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_Q-5AngDamYxHYoFs05ugEjs2y_epeqs',
    appId: '1:303720759928:ios:e8794807f49d2b7ee8e38d',
    messagingSenderId: '303720759928',
    projectId: 'diabetes-health-check',
    storageBucket: 'diabetes-health-check.appspot.com',
    iosClientId: '303720759928-ael7r25d3ta789nfe7doss9cc4fqlj8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.diabetesapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_Q-5AngDamYxHYoFs05ugEjs2y_epeqs',
    appId: '1:303720759928:ios:a140ae4049928779e8e38d',
    messagingSenderId: '303720759928',
    projectId: 'diabetes-health-check',
    storageBucket: 'diabetes-health-check.appspot.com',
    iosClientId: '303720759928-qnc7nq1a9rmal59oflgqvi4eaihhe9g1.apps.googleusercontent.com',
    iosBundleId: 'com.example.diabetesappsFe',
  );
}
